// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Seren.Modules.VoxMind.Speakers.Database;

#nullable disable

namespace Seren.Modules.VoxMind.Speakers.Database.Migrations
{
    [DbContext(typeof(VoxMindSpeakerDbContext))]
    [Migration("20260430093142_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Seren.Modules.VoxMind.Speakers.Database.SpeakerEmbeddingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AudioDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("InitialConfidence")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("idx_embeddings_profile");

                    b.ToTable("SpeakerEmbeddings");
                });

            modelBuilder.Entity("Seren.Modules.VoxMind.Speakers.Database.SpeakerProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AliasesJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DetectionCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("idx_profiles_lastseen");

                    b.ToTable("SpeakerProfiles");
                });

            modelBuilder.Entity("Seren.Modules.VoxMind.Speakers.Database.SpeakerEmbeddingEntity", b =>
                {
                    b.HasOne("Seren.Modules.VoxMind.Speakers.Database.SpeakerProfileEntity", "Profile")
                        .WithMany("Embeddings")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Seren.Modules.VoxMind.Speakers.Database.SpeakerProfileEntity", b =>
                {
                    b.Navigation("Embeddings");
                });
#pragma warning restore 612, 618
        }
    }
}
