export {
  Client,
  type ClientOptions,
  type ClientStatus,
  type WebSocketFactory,
} from './Client'
export { EventTypes, type EventTypeName } from './types/event-types'
export type {
  WebSocketEnvelope,
  EventMetadata,
  EventIdentity,
  ModuleIdentityDto,
  AnnouncePayload,
  AnnouncedPayload,
  HeartbeatPayload,
  ErrorPayload,
  TextInputPayload,
  ChatAttachmentInput,
  ChatAttachmentMetadata,
  VoiceInputPayload,
  ChatChunkPayload,
  ChatEndPayload,
  UserEchoPayload,
  AudioPlaybackPayload,
  LipsyncFramePayload,
  AvatarEmotionPayload,
  AvatarActionPayload,
  ChatHistoryRequestPayload,
  ChatHistoryBeginPayload,
  ChatHistoryItemPayload,
  ChatHistoryEndPayload,
  ChatClearedPayload,
  ChatAbortPayload,
  ChatProviderDegradedPayload,
  StreamErrorCategory,
} from './types/events'
export { generateId } from './utils/generate-id'