// Wire types for the Seren WebSocket protocol.
// Mirrors C# Seren.Contracts.Events — will be auto-generated by TypeGen later.

// ── Identity ────────────────────────────────────────────────────────────────

export interface ModuleIdentityDto {
  id: string
  pluginId: string
  version?: string
  labels?: Record<string, string>
}

export interface EventIdentity {
  id: string
  parentId?: string
}

export interface EventMetadata {
  source: ModuleIdentityDto
  event: EventIdentity
}

// ── Envelope ────────────────────────────────────────────────────────────────

export interface WebSocketEnvelope<T = unknown> {
  type: string
  data: T
  metadata: EventMetadata
}

// ── Payloads ────────────────────────────────────────────────────────────────

export interface AnnouncePayload {
  identity: ModuleIdentityDto
  name: string
  possibleEvents?: string[]
}

export interface AnnouncedPayload {
  identity: ModuleIdentityDto
  name: string
  index: number
}

export interface HeartbeatPayload {
  kind: 'ping' | 'pong'
  at: number
}

export interface ErrorPayload {
  message: string
  code?: string
}

export interface ChatChunkPayload {
  content: string
  characterId?: string
}

export interface ChatEndPayload {
  characterId?: string
}

export interface TextInputPayload {
  text: string
  sessionId?: string
}

export interface VoiceInputPayload {
  audioData: string
  format: string
  sessionId?: string
}

export interface AudioPlaybackPayload {
  audioData: string
  format: string
  characterId?: string
}

export interface LipsyncFramePayload {
  viseme: string
  startTime: number
  duration: number
  weight: number
  characterId?: string
}

export interface AvatarEmotionPayload {
  emotion: string
  characterId?: string
}

export interface AvatarActionPayload {
  action: string
  characterId?: string
}