// Wire types for the Seren WebSocket protocol.
// Mirrors C# Seren.Contracts.Events — will be auto-generated by TypeGen later.

// ── Identity ────────────────────────────────────────────────────────────────

export interface ModuleIdentityDto {
  id: string
  pluginId: string
  version?: string
  labels?: Record<string, string>
}

export interface EventIdentity {
  id: string
  parentId?: string
}

export interface EventMetadata {
  source: ModuleIdentityDto
  event: EventIdentity
}

// ── Envelope ────────────────────────────────────────────────────────────────

export interface WebSocketEnvelope<T = unknown> {
  type: string
  data: T
  metadata: EventMetadata
}

// ── Payloads ────────────────────────────────────────────────────────────────

export interface AnnouncePayload {
  identity: ModuleIdentityDto
  name: string
  possibleEvents?: string[]
}

export interface AnnouncedPayload {
  identity: ModuleIdentityDto
  name: string
  index: number
}

export interface HeartbeatPayload {
  kind: 'ping' | 'pong'
  at: number
}

/**
 * Error taxonomy mirroring `Seren.Contracts.Events.Payloads.StreamErrorCategory`.
 * Drives the UI's remediation affordance:
 * - `transient`  → show a Retry button (failure likely to clear on its own)
 * - `degraded`   → inform the user we already fell back to another provider
 * - `permanent`  → advise changing model or contacting support
 */
export type StreamErrorCategory = 'transient' | 'degraded' | 'permanent'

export interface ErrorPayload {
  message: string
  code?: string
  category?: StreamErrorCategory
  failedProvider?: string
}

export interface ChatChunkPayload {
  content: string
  characterId?: string
}

export interface ChatEndPayload {
  characterId?: string
}

/**
 * Single attachment joined to an `input:text` event. The hub base64-decodes
 * `content`, validates MIME + magic bytes + size, then either forwards the
 * bytes as an OpenClaw multimodal attachment (images) or extracts their
 * text server-side and folds the result into the user message (PDF / TXT /
 * MD / CSV). Size caps + MIME whitelist are exposed via
 * `GET /api/chat/attachments/constraints` — fetch that endpoint on startup
 * and pre-validate client-side so users get instant feedback.
 */
export interface ChatAttachmentInput {
  mimeType: string
  fileName: string
  /** Raw byte size of the original file (before base64 encoding). */
  byteSize: number
  /** Base64-encoded content. No `data:` URI prefix. */
  content: string
}

/** Echo-side metadata for one attachment — light version of
 * `ChatAttachmentInput` without the payload bytes. The originating tab
 * has the File locally for its thumbnail; peer tabs render a placeholder
 * keyed on `attachmentId`. */
export interface ChatAttachmentMetadata {
  mimeType: string
  fileName: string
  byteSize: number
  /** Opaque server-minted id; stable only for the life of the echo. */
  attachmentId: string
}

export interface TextInputPayload {
  text: string
  sessionId?: string
  /** Optional LLM model override (e.g. "openai/gpt-4o-mini"). When
   * set, takes precedence over the active character's AgentId. */
  model?: string
  /** Stable id of the local optimistic bubble. The hub echoes it back
   * to every other peer on the session via `output:chat:user` so they
   * render the same message with a consistent id; the sender uses it
   * to ignore the echo of its own message. */
  clientMessageId?: string
  /** Optional images and documents joined to the message. The hub caps
   * size + count per `AttachmentConstraints` — pre-validate against the
   * `/api/chat/attachments/constraints` endpoint to avoid round-trips. */
  attachments?: ChatAttachmentInput[]
}

/** Broadcast user-turn echo — fan-out of `input:text` to every other
 * peer on the session. The originating tab already has this message
 * in its store under `messageId`; it should treat the echo as a no-op. */
export interface UserEchoPayload {
  messageId: string
  text: string
  timestampMs: number
  /** Metadata for each attachment the sender joined. Content bytes are
   * not echoed — peer tabs render a placeholder until a later persistent
   * attachment endpoint is added. */
  attachments?: ChatAttachmentMetadata[]
}

export interface VoiceInputPayload {
  audioData: string
  format: string
  sessionId?: string
  /** Optional LLM model override. See TextInputPayload.model. */
  model?: string
  /** Stable id of the local optimistic bubble. The hub reuses it as the
   * `messageId` of the eventual `output:chat:user` echo so the originating
   * tab can replace the placeholder with the actual transcription instead
   * of duplicating the bubble. */
  clientMessageId?: string
  /** Optional STT engine override (`"parakeet"` | `"whisper-{tiny|base|small|
   * medium|large}"`). When undefined the server router uses its configured
   * default. Set by the UI from the `seren/voxmind/sttEngine` persisted
   * preference. */
  sttEngine?: string
  /** Optional STT language override (ISO 639-1 code, e.g. `"fr"` / `"en"`).
   * When undefined or empty the engine's configured default is used; for
   * Whisper that means sherpa-onnx auto-detect. Set by the UI from the
   * `seren/voice/sttLanguage` persisted preference. */
  sttLanguage?: string
}

/** Payload of an `input:voice:transcribe` event — STT-only request. The
 * server runs the audio through the configured STT provider and replies
 * with `output:voice:transcript` on the same connection. No chat-stream is
 * started, no LLM is invoked. Used by the UI "dictate into text input"
 * flow where the user reviews the transcription before pressing Send. */
export interface VoiceTranscribePayload {
  audioData: string
  format: string
  /** Optional client-minted correlation id, echoed back in the matching
   * VoiceTranscriptPayload so the UI can resolve the right in-flight
   * promise (multiple concurrent dictate presses, multi-tab). */
  requestId?: string
  /** Optional STT engine override. Same semantics as
   * `VoiceInputPayload.sttEngine`. */
  sttEngine?: string
  /** Optional STT language override. Same semantics as
   * `VoiceInputPayload.sttLanguage`. */
  sttLanguage?: string
}

/** Payload of an `output:voice:transcript` event — STT result returned to
 * the originating peer of an `input:voice:transcribe` request. Sent unicast
 * (not broadcast) since this transcription has not yet been committed to
 * chat. */
export interface VoiceTranscriptPayload {
  /** Echo of VoiceTranscribePayload.requestId. */
  requestId?: string
  text: string
  language?: string
  confidence?: number
}

export interface AudioPlaybackPayload {
  audioData: string
  format: string
  characterId?: string
}

export interface LipsyncFramePayload {
  viseme: string
  startTime: number
  duration: number
  weight: number
  characterId?: string
}

export interface AvatarEmotionPayload {
  emotion: string
  characterId?: string
}

export interface AvatarActionPayload {
  action: string
  characterId?: string
}

// ── Chat history hydration ──────────────────────────────────────────────────

/** Sent by the client to request older messages (scroll-back pagination). */
export interface ChatHistoryRequestPayload {
  /** Maximum number of messages to return. */
  limit?: number
  /** Cursor — only messages with messageId older than this are returned. */
  before?: string
}

/**
 * Emitted by the server right before the first item of an initial
 * hydration batch (not emitted for scroll-back). Tells the client to
 * drop any currently-displayed messages so the upcoming batch is the
 * single source of truth — critical after a reconnect, where local
 * live messages would otherwise duplicate with re-hydrated copies
 * that carry the server's messageId rather than the client-generated one.
 */
export interface ChatHistoryBeginPayload {
  reset: boolean
}

/** One persisted message pushed by the server during hydration. */
export interface ChatHistoryItemPayload {
  messageId: string
  role: 'user' | 'assistant' | 'system'
  content: string
  timestamp: number
  emotion?: string
}

/** End-of-burst marker for a hydration / scroll-back batch. */
export interface ChatHistoryEndPayload {
  hasMore: boolean
  oldestMessageId?: string
}

/** Broadcast confirmation that the conversation was reset. */
export interface ChatClearedPayload {
  at: number
}

/**
 * Informational broadcast sent when the chat pipeline transparently retried
 * the same provider or fell back to another one. Does NOT close the stream
 * — an `output:chat:end` still follows once the successful attempt
 * completes. Clients use it to show a non-blocking notice so the user
 * understands why the reply may come from a different model than selected.
 */
export interface ChatProviderDegradedPayload {
  /** Provider id that failed (e.g. `ollama/kimi-k2.6:cloud`). */
  from: string
  /** Provider id being tried next. Equal to `from` during a same-model retry. */
  to: string
  /** Machine-readable reason the previous attempt failed. */
  reason: 'idle_timeout' | 'total_timeout' | 'error'
  /** 1-indexed attempt number that just failed. */
  attempt: number
}

// ── Stream cancellation ─────────────────────────────────────────────────────

/**
 * Sent by a client to ask the hub to abort the active chat run upstream
 * (OpenClaw `chat.abort`). Drives the Stop button shown during streaming.
 *
 * `runId` matches the `clientMessageId` the originating tab sent on
 * `input:text` (the hub uses it as both the optimistic-bubble id and the
 * upstream `idempotencyKey`/runId). When omitted the hub aborts whatever
 * run is currently active for the shared session.
 */
export interface ChatAbortPayload {
  runId?: string
}