// Event type name constants mirroring C# Seren.Contracts.Events.EventTypes.

export const EventTypes = {
  TransportHello: 'transport:hello',
  TransportHeartbeat: 'transport:connection:heartbeat',
  ModuleAuthenticate: 'module:authenticate',
  ModuleAuthenticated: 'module:authenticated',
  ModuleAnnounce: 'module:announce',
  ModuleAnnounced: 'module:announced',
  ModuleDeAnnounced: 'module:de-announced',
  RegistryModulesSync: 'registry:modules:sync',
  InputText: 'input:text',
  InputVoice: 'input:voice',
  InputVoiceTranscribe: 'input:voice:transcribe',
  OutputVoiceTranscript: 'output:voice:transcript',
  InputChatHistoryRequest: 'input:chat:history:request',
  InputChatReset: 'input:chat:reset',
  InputChatAbort: 'input:chat:abort',
  OutputChatChunk: 'output:chat:chunk',
  OutputChatEnd: 'output:chat:end',
  OutputChatThinkingStart: 'output:chat:thinking:start',
  OutputChatThinkingEnd: 'output:chat:thinking:end',
  OutputChatUser: 'output:chat:user',
  OutputChatHistoryBegin: 'output:chat:history:begin',
  OutputChatHistoryItem: 'output:chat:history:item',
  OutputChatHistoryEnd: 'output:chat:history:end',
  OutputChatCleared: 'output:chat:cleared',
  OutputChatProviderDegraded: 'output:chat:provider-degraded',
  AudioPlaybackChunk: 'audio:playback:chunk',
  AudioLipsyncFrame: 'audio:lipsync:frame',
  AvatarEmotion: 'avatar:emotion',
  AvatarAction: 'avatar:action',
  Error: 'error',
} as const

export type EventTypeName = (typeof EventTypes)[keyof typeof EventTypes]