export { default as ChatPanel } from './components/ChatPanel.vue'
export { default as AvatarStage } from './components/AvatarStage.vue'
export { default as CharacterSelector } from './components/CharacterSelector.vue'
export { default as SettingsPanel } from './components/SettingsPanel.vue'
export { useChatStore } from './stores/chat'
export type { ChatMessage, InitClientOptions } from './stores/chat'
export { useCharacterStore } from './stores/character'
export type { CharacterDto, CreateCharacterInput } from './stores/character'
export { useSettingsStore } from './stores/settings'
export type { SerenSettings } from './stores/settings'
export { encodeWavBase64 } from './utils/wav-encoder'